### ISSUE TITLE
64drive: Byteswap on load (`cart_card_byteswap`) makes FatFs functions unusable

### ISSUE THREAD

**Issue by Polprzewodnikowy** [devwizard64/libcart#1]
64drive's "byteswap on load" command affects both transfer types (to SDRAM and to buffer). Setting this option makes FatFs read corrupted data when any read operation is performed. Ideally byteswap should be disabled when "read sector into buffer" command is used.

**Comment by devwizard64** [comment]
`cart_card_byteswap` is now a flag you set in code that will only apply to SDRAM read.
